---
title: "平成28年度社会医学実習--実施例"
author: "王　超辰"
date: "2016年6月30日"
output:
  pdf_document:
    fig_caption: yes
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
  word_document: default
fontsize: 11pt
header-includes:
- \usepackage{xltxtra}
- \usepackage{xeCJK}
- \setCJKmainfont{IPAPMincho}
- \setCJKmonofont{Noto Sans CJK SC}
- \XeTeXlinebreaklocale "ja"
- \XeTeXlinebreakskip=0pt
- \XeTeXlinebreakpenalty=0
linkcolor: blue
csl: advances-in-alzheimers-disease.csl
sansfont: IPAPGothic
bibliography: refs.bib
---

# 例：日本人(40歳以上)肝がん罹患の年齢，出生コホート，時期効果分析

#  必要となるパッケージ：
```{r eval=FALSE}
install.packages("XLConnect") #エクセルファイルのデータを読み込む用
install.packages("ggplot2") #グラフ作成用
install.packages("reshape2") #データ操作する用
#  ダウンロードされたエクセルファイルの4番目のsheet"rate"だけ抽出し，
#  名前を付けてデスクトップに保存する．例："cancer_incidence(1975-2011)rate.xls"
setwd("C://Users/xxxxx/Desktop") #自分のPCのデスクトップのアドレスに書き換える．
#　通常は"C://Users/自分のユザー名/Desktop/",(円マーク"￥"をスラッシュ"/"に変更)
```

#  データのマネージメント
```{r cache=TRUE, message=FALSE}
library(XLConnect) #パッケージのローディング

rate.all <- readWorksheetFromFile("cancer_incidence(1975-2011)rate.xls",
                                  sheet = 1)

#  さっき抽出された，がん罹患データをRに読み込む
#  変数名の変更: 
names(rate.all) <- gsub("X", "age", names(rate.all))
# ここから漢字の前に半角の空白" "が出てくるが，無視して(半角空白なしで)書くことにする．
names(rate.all) <- gsub("歳", "", names(rate.all)) 
names(rate.all) <- gsub("以上", "plus", names(rate.all))
names(rate.all) <- gsub("診断年", "Dia_yr", names(rate.all))
names(rate.all) <- gsub("\\.", "_", names(rate.all))
#  チェックするために，最初の6行を示す
head(rate.all)
```

#  肝がん*罹患率*のグラフを作成する
```{r cache=TRUE, warning=FALSE, fig.height=6.5, fig.width=7, fig.showtext=TRUE} 

#  男女計のデータだけを抽出する：
rate.hepatic <- subset(rate.all, 部位 == "肝臓" & 性別 == "男女計")
#  データの形を変更する wide -> long
library(reshape2)
rate.hepatic.melt <- melt(data= rate.hepatic,
                measure.vars  = names(rate.hepatic)[grep("age",
                                                  names(rate.hepatic))],
                variable.name = "Age_Range",
                value.name    = "Incidence_Rate")
#  アンダーバーをハイフォンに変更
names(rate.hepatic.melt$Age_Range) <- gsub("_", "-", 
                                 as.character(rate.hepatic.melt$Age_Range))
#　チェックするために，最初の6行を示す
head(rate.hepatic.melt)
```

```{r cache=TRUE, warning=FALSE, fig.height=6.5, fig.width=7, fig.showtext=TRUE} 
#  診断された年を10年ごとにカテゴリ化する
rate.hepatic.melt$Dia_yr10 <- cut(rate.hepatic.melt$Dia_yr, dig.lab=10, 
                                  right = FALSE,
                                  breaks = seq(from = 1975, to = 2015, by = 10))

#  各年齢群カテゴリに下限値の年齢として名前を付ける
rate.hepatic.melt$age <- seq(from = 0, to = 85, 
                             by = 5)[rate.hepatic.melt$Age_Range]

#  生まれた年の計算
rate.hepatic.melt$Birth_yr <- with(rate.hepatic.melt, 
                                   Dia_yr - age)

#  生まれた年(出生コホート)を10年ごとカテゴリ化する
rate.hepatic.melt$Birth_yr10 <- cut(rate.hepatic.melt$Birth_yr,dig.lab=10, 
                                  right = FALSE,
                          breaks = seq(from = 1890, to = 2020, by = 10))

#　40歳以上に限定する:

rate.hepatic.melt.40 <- subset(rate.hepatic.melt, 
                               (as.numeric(Age_Range) > 8))

#  データをチェックするために，最初の20行を示す
head(rate.hepatic.melt.40, 20)



#  グラフ1作成
library(ggplot2)

#  横軸に調査年，５歳ごと年齢階級別(Age_Range)罹患率

ggplot(data = rate.hepatic.melt.40,
       mapping = aes(x = Dia_yr, y = Incidence_Rate,
                     color = Age_Range)) + 
  geom_line(size = 1.3) +
  geom_point() +
    xlab("調査年") + 
    ylab("発症率(対人口10万人)") + 
    labs(title = 
           "グラフ１：5歳ごと年齢階級別罹患率\n(40歳以上)") + 
    theme_bw() +
    theme(legend.key = element_blank(),
          axis.text.x = element_text(angle=0, vjust=1))　+ 
  scale_y_continuous(breaks = seq(0,170, 10)) + 
  scale_x_continuous(breaks = seq(1890, 2020, 5)) +
  scale_color_brewer(palette = "Set3") 

```

```{r cache=TRUE, warning=FALSE, fig.height=6.5, fig.width=7, fig.showtext=TRUE} 
#  グラフ2作成

#　網掛けデータ
rect <- data.frame(xmin = 1930, xmax = 1935, ymin=-Inf, ymax=Inf)

#  横軸に生まれた年，診断された年齢(Age_Range)により可視化

ggplot(data = rate.hepatic.melt.40,
       mapping = aes(x = Birth_yr, y = Incidence_Rate,
                     color = Age_Range)) + 
  geom_line(size = 1.3) +
  geom_point() +
    xlab("出生年") + 
    ylab("発症率(対人口10万人)") + 
    labs(title = 
           "グラフ２：出生年・年齢別肝がん罹患率\n(40歳以上)") + 
    theme_bw() +
    theme(legend.key = element_blank(),
          axis.text.x = element_text(angle=-10, vjust=1))　+ 
  scale_y_continuous(breaks = seq(0,170, 10)) + 
  scale_x_continuous(breaks = seq(1890, 2020, 5)) +
  scale_color_brewer(palette = "Set3") + 
  geom_rect(data = rect, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), 
            fill = "#A2B5CD", inherit.aes = FALSE, alpha=0.5)
 

```

## グラフ２：肝臓がんの罹患率は，1930年代前半生まれにピークがあることがわかりる（濃い網掛け）．この年代生まれは，C型肝炎ウイルスの陽性割合の高い世代と一致している．


```{r cache=TRUE, warning=FALSE, fig.height=6.5, fig.width=7, fig.showtext=TRUE} 
#  グラフ3作成
#  横軸に診断された時年齢の５歳ごと階級(Age_Range)，出生コホートにより可視化


ggplot(data = rate.hepatic.melt.40,
       mapping = aes(x = Age_Range, y = Incidence_Rate, group=factor(Birth_yr),
                     color = Birth_yr10)) + 
  geom_line(size=1.3) +
  geom_point() +
    xlab("診断年齢") + 
    ylab("発症率(対人口10万人)") + 
    labs(title = 
           "グラフ３：日本人の肝がん罹患率\n (出生コホートによる)") + 
    theme_bw() +
    theme(legend.key = element_blank(),
          axis.text.x = element_text(angle=10, vjust=1))　+ 
  scale_y_continuous(breaks = seq(0,170, 10))+
  scale_color_brewer(palette = "Paired")


```

